[project]
name = "hexlet-code"
version = "0.1.0"
description = "Анализатор страниц"
readme = "README.md"
authors = [{name = "pavel", email = "paveldidko@gmail.com"},]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.2"
gunicorn = "^20.1.0"
python-dotenv = "^0.21.0"